[package]
name = "tsu"
version = "0.1.0"
authors = ["Cameron Howell <me@crhowell.com>"]
edition = "2024"
publish = false

[lints.rust]
unsafe_code = "forbid"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
crossterm = "0.29.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt", "env-filter"] }
