theme = "gruvbox-dark-soft.json"

log_file = "/tmp/tsu.log"

[keys.insert]
Enter = "InsertNewLine"
Backspace = "DeletePreviousChar"
"Up" = "MoveUp"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
Esc = { EnterMode = "Normal" }

[keys.normal]
"Up" = "MoveUp"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"k" = "MoveUp"
"j" = "MoveDown"
"h" = "MoveLeft"
"l" = "MoveRight"
"0" = "MoveToLineStart"
"Home" = "MoveToLineStart"
"$" = "MoveToLineEnd"
"End" = "MoveToLineEnd"
"Delete" = "DeleteCharAtCursor"
"PageUp" = "PageUp"
"PageDown" = "PageDown"
"o" = [ { EnterMode = "Insert" }, "InsertLineBelow" ]
"O" = [ { EnterMode = "Insert" }, "InsertLineAbove" ]
"i" = { EnterMode = "Insert" }
"d" = { "d" = "DeleteCurrentLine" }
"g" = { "g" = "MoveToTopOfBuffer", "h" = "MoveToLineStart", "l" = "MoveToLineEnd", "e" = "MoveToBottomOfBuffer" }
"G" = "MoveToBottomOfBuffer"
"z" = { "z" = "CenterView", "t" = "MoveToTop", "b" = "MoveToBottom" }
"u" = "Undo"
":" = { EnterMode = "Command" }
"Ctrl-e" = "MoveViewDownOneLine"
"Ctrl-y" = "MoveViewUpOneLine"

[keys.command]
Esc = { EnterMode = "Normal" }

[commands]
"write" = "Save"
"quit" = "Quit"
